name: collectstatic

on:
  push:
    # branches:
    #  - main

jobs:
  collectstatic:
    runs-on: ubuntu-latest
    environment: collectstatic

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/authenticate_gcloud.sh
        ./scripts/authenticate_gcloud.sh
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Collect the static files
      run: |
        chmod +x ./scripts/collectstatic.sh
        ./scripts/collectstatic.sh
      env:
        ADMINS: ${{ secrets.ADMINS }}
        ADMIN_URL: ${{ secrets.ADMIN_URL }}
        DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
        DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
        GCP_STORAGE_BUCKET_NAME: ${{secrets.GCP_STORAGE_BUCKET_NAME }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        DESTINATION_STORAGE_BUCKET_NAMES: ${{ secrets.DESTINATION_STORAGE_BUCKET_NAMES }}
