name: collectstatic

on:
  pull_request:
    branches:
      - main
    types:
      - closed

  push:
    branches: [main]

jobs:
  collectstatic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/authenticate_gcloud.sh
        ./scripts/authenticate_gcloud.sh
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Collect the static files into STATIC_ROOT (Cloud Storage)
      run: |
        pipenv run python manage.py collectstatic --no-input
      env:
        # Django Core
        DJANGO_SETTINGS_MODULE: config.settings.production

        # Admin
        ADMINS: ${{ secrets.ADMINS }}
        ADMIN_URL: ${{ secrets.ADMIN_URL }}

        # Email
        DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
        DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}

        # Google Cloud
        GCP_STORAGE_BUCKET_NAME: ${{secrets.GCP_STORAGE_BUCKET_NAME}}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Submit test coverage data to coverage.io
      run: pipenv run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
