name: collectstatic

on:
  pull_request:
    branches: [main, prod]
    types:
      - closed

  push:
    # branches: [main]

jobs:
  collectstatic_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/authenticate_gcloud.sh
        ./scripts/authenticate_gcloud.sh
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Collect the static files into STATIC_ROOT (Cloud Storage)
      run: |
        pipenv run python manage.py collectstatic --no-input
        pipenv run python manage.py test
      env:
        # Django Core
        DJANGO_SETTINGS_MODULE: config.settings.production

        # Admin
        ADMINS: ${{ secrets.ADMINS }}
        ADMIN_URL: ${{ secrets.ADMIN_URL }}

        # Database
        DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:${{ job.services.postgres.ports[5432] }}/${{ secrets.DB_NAME }}

        # Email
        DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
        DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}

        # Google Cloud
        GCP_STORAGE_BUCKET_NAME: ${{secrets.GCP_STORAGE_BUCKET_NAME}}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
