name: Continuous Deployment

on:
  pull_request:
    branches: [main, prod]
    types:
      - closed

  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/decrypt_secret.sh
        ./scripts/decrypt_secret.sh
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE_PASSPHRASE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE_PASSPHRASE}}

    - name: Deploy to App Engine Standard
      run: |
        pipenv run python manage.py collectstatic --no-input
      env:
        # Django Core
        DJANGO_SETTINGS_MODULE: config.settings.production

        # Admin
        ADMINS: ${{ secrets.ADMINS }}
        ADMIN_URL: ${{ secrets.ADMIN_URL }}

        # Email
        DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
        DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}

        # Google Cloud
        GCP_STORAGE_BUCKET_NAME: ${{secrets.GCP_STORAGE_BUCKET_NAME}}
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
