name: Test

on:
  push:
  pull_request:
    branches: [ main, prod ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
        services:
          postgres:
            image: postgres:13
            env:
              POSTGRES_DB: ${{ secrets.DB_NAME }}
              POSTGRES_USER: ${{ secrets.DB_USER }}
              POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
            ports:
            # will assign a random free host port
            - 5432/tcp
            # needed because the postgres container does not provide a healthcheck
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run Tests
      run: |
        pipenv run coverage run manage.py test
      env:
        # Django Core
        DJANGO_SETTINGS_MODULE: config.settings.base

        # Database
        DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:${{ job.services.postgres.ports[5432] }}/${{ secrets.DB_NAME }}

        # Email
        DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
        DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}

    - name: Submit test coverage data to coverage.io
      run: pipenv run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
